---
- name: include OS-specific variables.
  include_vars: "{{ ansible_os_family|lower }}.yaml"
  when: ansible_os_family == 'RedHat'

- name: install required packages
  become: yes
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: enable SSH forwarding (tunnel through Bastion)
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^AllowTcpForwarding.*'
    replace: 'AllowTcpForwarding yes'
    backup: yes
  notify:
    # Restart SSHD after last replacement
    - restart sshd
