---
- name: include OS-specific variables.
  include_vars: "{{ ansible_os_family|lower }}.yaml"
  when: ansible_os_family == 'RedHat'

- name: install required packages
  become: yes
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: disable pwd login for user {{ ansible_user }}
  user:
    name: "{{ ansible_user }}"
    password_lock: yes

- include_tasks: sshd.yaml
- include_tasks: journalctl.yaml
